Web.Mvc/Controllers/AppointmentController.cs
using DAL;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Model;
using System;
using System.Buffers.Text;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Security.Policy;
using System.Threading.Tasks;
using Web.Mvc.Extentions;
//using System.Web.Mvc;
using Web.Mvc.Models;

namespace Web.Mvc.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly ILogger<AppointmentController> _logger;
        private readonly IConfiguration _config;
        private ILoggerFactory _factory;
        private string _connectionString;
        private SqlConnection connection;

        public AppointmentController(ILogger<AppointmentController> logger, IConfiguration config,ILoggerFactory factory)
        {
            _logger = logger;
            _config=config;
            _factory = factory;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromRoute] int? id)
        {
            Appointment viewModel = new Appointment();
            if (id > 0)
            {                               
                AppointmentAccess aa = new AppointmentAccess(_config,_factory.CreateLogger<AppointmentAccess>());
                viewModel = await aa.GetAppointmentById(id.Value);
                var doctorList = await aa.AllDoctorList();
                viewModel.DoctorList = doctorList.ToViewModel();
                viewModel.SelectedDoctorId = viewModel.DoctorId;
                                
            }
            return View("appointment", viewModel);            
        }

        //[HttpPost]
        //public IActionResult Index([FromBody] Appointment appointment)
        //{
        //        appointment.StatusId = (int)StatusEnum.Scheduled;
        //        AppointmentAccess appointmentAccess = new AppointmentAccess(_config);
        //        appointmentAccess.AddAppointment(appointment);
        //        return Json(new { message = "success"});            
        //}
       
        [HttpGet]
        public IActionResult PetId()
        {           
            var viewModel = new PetTypeModel();
            return View(viewModel);
        }
        
        [HttpPost]
        public async Task<IActionResult> PetId([FromBody] PetTypeModel model)
        {
            if (model == null || model.PetTypeValue < 1 || model.PetTypeValue > 3)
            {
                return BadRequest("Invalid pet type value.");
            }

            try
            {
                using (SqlConnection con = new SqlConnection(_connectionString))
                {
                    await connection.OpenAsync();
                    using (var command = new SqlCommand("dbo.GetBreedTypeListByPetTypeId", connection))
                    {
                        command.CommandType = CommandType.StoredProcedure;
                        command.Parameters.AddWithValue("@PetTypeValue", model.PetTypeValue);
                        await command.ExecuteNonQueryAsync();
                    }
                }

                return Ok();
            }
            catch (Exception ex)
            {
                // Handle exceptions, log errors, etc.
                return StatusCode(500, "An error occurred while processing the request.");
            }
        }
       

        [HttpGet]
        public IActionResult GetPetTypes()
        {
            // Replace this sample data with data from your database
            var petTypes = new List<SelectListItem>
        {
            new SelectListItem { Value = "1", Text = "Dog" },
            new SelectListItem { Value = "2", Text = "Cat" },
            new SelectListItem { Value = "3", Text = "Rabbit" }
        };

            return Json(petTypes);
        }

        
        [HttpGet]
        public async Task<IActionResult> GetBreedsByPetTypeId([FromQuery]int petTypeId)
        {
            AppointmentAccess a = new AppointmentAccess(_config, _factory.CreateLogger<AppointmentAccess>());

            List<Breed> breedList = await a.GetBreedsByPetTypeId(petTypeId);
            return Json(breedList);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAppointment([FromBody] Appointment request)
        {
            
            try
            {
                AppointmentAccess appointmentAccess = new AppointmentAccess(_config, _factory.CreateLogger<AppointmentAccess>());

                if (request.Id > 0)
                {
                   await appointmentAccess.UpdateAppointmentById(request);
                }
                else 
                {
                    request.StatusId = (int)StatusEnum.Scheduled;
                    appointmentAccess.AddAppointment(request);
                }
                
                return Json(new { message = "success"});
            }
            catch (System.Exception)
            {
                return StatusCode(500, new { messege = "Error", discription = "an error occured while proessing ur request" });

            }

        }
        [HttpGet]
        public async Task<ActionResult<List<Doctor>>> GetAllDoctors()
        {
            try
            {
                AppointmentAccess a = new AppointmentAccess(_config, _factory.CreateLogger<AppointmentAccess>());
                List<Doctor> doctorList = await a.AllDoctorList();
                return Ok(doctorList);
            }
            catch (Exception ex)
            {
                // Handle exceptions here
                return StatusCode(500, "An error occurred while fetching doctors.");
            }
        }

        [HttpGet]
        public async Task<ActionResult<AppointmentListContainer>> GetAllAppointments([FromQuery]AppointmentSearchParms request)
        {
            try
            {              

                int? doctorId = request.SelectedDoctorId == 0 ? null : request.SelectedDoctorId ;
                int? statusId = request.SelectedStatusId == 0 ? null : request.SelectedStatusId;
                AppointmentAccess apt = new AppointmentAccess(_config, _factory.CreateLogger<AppointmentAccess>());
                List<Appointment> appointmentlist = await apt.GetAllAppointmentsDapper(request.CurrentPage, request.PageSize, doctorId, statusId);
                List<Status> statuslist = await apt.GetAllStatus();
                List<Doctor> doctorList = await apt.AllDoctorList();
                AppointmentListContainer container = new AppointmentListContainer();
                container.SearchParms = new AppointmentSearchParms();                
                container.SearchParms.StatusList = statuslist.ToViewModel();
                container.SearchParms.DoctorList = doctorList.ToDoctorViewModel();
                container.AppointmentList = appointmentlist;
                if(appointmentlist.Count > 0)
                {
                 container.PagingInfo = new Pager(appointmentlist.First().TotalRecords, request.CurrentPage, request.PageSize);
                }
                return View("AppointmentList", container);
            }
            catch (DivideByZeroException ex)
            {
                // Handle exceptions here
                _logger.LogError(ex, "error occured while retreving appointment list");
                return StatusCode(500, "An error occurred while fetching doctors.");
            }
            catch (Exception ex)
            {
                // Handle exceptions here
                return StatusCode(500, "An error occurred while fetching doctors.");
            }
        }


        [HttpDelete]
        public ActionResult Delete(int deleteId)
        {
            try
            {

                AppointmentAccess appointmentAccess = new AppointmentAccess(_config, _factory.CreateLogger<AppointmentAccess>());
                appointmentAccess.DeleteAppointment(deleteId);

                // Assuming the operation was successful, return a JSON success response
                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                // Handle any exceptions that occur during the deletion process
                // You can log the error or return an error response as needed
                return Json(new { success = false, errorMessage = ex.Message });
            }
        }
        [HttpGet]
        public async Task<ActionResult<Appointment>> GetAppointmentById(int id )
        {
            try
            {
                AppointmentAccess apt = new AppointmentAccess(_config, _factory.CreateLogger<AppointmentAccess>());
                Appointment appointment = await apt.GetAppointmentById(id);
                return View("editappointment", appointment);
            }
            catch (Exception ex)
            {
                // Handle exceptions here
                return StatusCode(500, "An error occurred while fetching doctors.");
            }
        }
        [HttpGet]
        public IActionResult EditAppointment()
        {
            
            return View("appointment"); 
        }
              
        


    }
}

    

Web.Mvc/Controllers/DoctorController.cs
using DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Model;
using System.Diagnostics;
using System.Net;
//using System.Web.Mvc;
using Web.Mvc.Models;

namespace Web.Mvc.Controllers
{
    public class DoctorController : Controller
    {
        private readonly ILogger<DoctorController> _logger;
        private readonly IConfiguration _config;

        public DoctorController(ILogger<DoctorController> logger, IConfiguration config)
        {
            _logger = logger;
            _config=config;
        }

        [HttpGet]        
        public IActionResult Index()
        {
            Doctor doctor = new Doctor();
            return View(doctor);
        }
        
        [HttpPost]
        public IActionResult Index([FromBody] Doctor doctor)
        {
            try
            {
                DoctorAccess doctorAccess = new DoctorAccess(_config);
                doctorAccess.AddDoctor(doctor);
                return Json(new { message = "success",firstName = doctor.FirstName });
            }
            catch (System.Exception)
            {
                return StatusCode(500,new { messege = "Error",discription="an error occured while proessing ur request" });
               
            }
           
        }

        public IActionResult Privacy()
        {
            ViewData["Jeffin"] = "This is my test Privacy policy";
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
        
    }
}

Web.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/pet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.Mvc.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctor" asp-action="Index">Create Doctor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="Index">Create Appointment</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointment" asp-action="GetAllAppointments" asp-route-currentPage="1" asp-route-pageSize="10">Appointment List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 jeffin1 jeffin2">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/pet.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web.Mvc/Views/Shared/_Pagination.cshtml
@model Web.Mvc.Models.Pager

@if (Model.EndPage > 1)
{
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a class="lnk-pager" data-currentpage="1" href="~/Appointment/GetAllAppointments">First</a> &nbsp|   &nbsp
            </li>
            <li>
                <a class="lnk-pager" data-currentpage="@(Model.CurrentPage - 1)" href="~/Appointment/GetAllAppointments?page=@(Model.CurrentPage - 1)">Previous</a> &nbsp|   &nbsp
            </li>
        }

        @for (var pageNo = Model.StartPage; pageNo <= Model.EndPage; pageNo++)
        {
            <li class="@(pageNo == Model.CurrentPage ? "active" : "")">
                <a class="lnk-pager" data-currentpage="@pageNo" href="Appointment/GetAllAppointments?page=@pageNo">@pageNo</a>&nbsp|   &nbsp
            </li>
        }

        @if (Model.CurrentPage < Model.TotalPages)
        {
            <li>
                <a class="lnk-pager" data-currentpage="@(Model.CurrentPage + 1)" href="~/Appointment/GetAllAppointments?page=@(Model.CurrentPage + 1)">Next</a>&nbsp|   &nbsp
            </li>
            <li>
                <a class="lnk-pager" data-currentpage="@(Model.TotalPages)" href="~/Appointment/GetAllAppointments?page=@(Model.TotalPages)">Last</a>&nbsp|   &nbsp
            </li>
        }
    </ul>
}

Web.Mvc/Views/Shared/_Search.cshtml
@model AppointmentSearchParms

<div class="row">
    <div class="col-md-6">
        <label for="searchInput">Select Doctor Name</label>       
        @Html.DropDownListFor(m => m.SelectedDoctorId,Model.DoctorList,new{@id="ddlDoctor",@class="form-control"})

    </div>
    <div class="col-md-6">
        <label>Status</label>        
        @Html.DropDownListFor(m => m.SelectedStatusId,Model.StatusList,new{@id="statusDropdown",@class="form-control"})
    </div>
    <div class="row margin-top-10">
        <div class="col-md-6">
            <button type="button" id="searchButton" class="btn btn-primary" style="width:50%;">Search</button>
        </div>        
    </div>    
</div>